//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace POLM.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class Entities : DbContext
    {
        string SQLConnectString_ODC = "User ID=extdev;Password=extuser;Data Source=(DESCRIPTION = (ADDRESS_LIST= (ADDRESS = (PROTOCOL = TCP)(HOST = 10.198.9.17)(PORT = 1521))) (CONNECT_DATA = (SERVICE_NAME = orazhs)))";

        public Entities()
            : base("name=Entities")
        {
            this.Database.Connection.ConnectionString = SQLConnectString_ODC;
        }

        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<POLM_CONFIG> POLM_CONFIG { get; set; }
        public virtual DbSet<POLM_WI_OV> POLM_WI_OVSet { get; set; }
    }
}
