//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace POLM.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class POLM_CONFIG
    {
        public decimal ID { get; set; }
        public string FAMILY { get; set; }
        public string TYPE { get; set; }
        public string PARKEY { get; set; }
        public string PARVALUE { get; set; }
        public string MACHINE { get; set; }
        public string REMARK { get; set; }
        public string DATA { get; set; }
    }
}
