//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace POLM.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class POLM_WI_OV
    {
        public decimal ID { get; set; }
        public string MCTYPE { get; set; }
        public string PROJECT { get; set; }
        public string FILENAME { get; set; }
        public string WORKSHEET { get; set; }
        public string DOCNUM { get; set; }
        public string DOCREV { get; set; }
        public string REMARK { get; set; }
        public Nullable<System.DateTime> UPDATETIME { get; set; }
        public string LINE { get; set; }
        public Nullable<System.DateTime> EFFDATE { get; set; }
    }
}
